spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8761

eureka:
  client:
    fetch-registry: false # los clientes van a necesitar fetch-registry y register-with-eureka a true
    register-with-eureka: false