spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    fetch-registry: false # los clientes van a necesitar fetch-registry y register-with-eureka a true
    register-with-eureka: false