services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: rogerserra
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres # este es el nombre de cuando vamos a pgadmin, add new server, host name/address. Si pgadmin no corriera en docker, se tendria que poner localhost
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres # este es el nombre de cuando vamos a pgadmin, add new server, host name/address
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

networks: # para que los contenedores hablen entre si
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: