# CUIDADO con los anidados, el jpa lo tenia donde no tocaba y no creaba la tabla en postgres ni se veia en pgadmin
server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/fraud # aun no es un contenedor, sino tocaria conectar via network
    username: rogerserra
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true